### PR TITLE
add source_component.display_value for resistor and capacitor

### LINKED ISSUE #463: Populate `source_component.display_value` for resistors and capacitors
/bounty $7

### PR DESCRIPTION
**Pull request by Anshgrover23**
/claim #463 
Fixes #463

### CODE REVIEW

**Review by seveibar — CHANGES_REQUESTED** [review]
See remark here: https://github.com/tscircuit/core/issues/463#issuecomment-2564643616

don't do the dangerous unknown cast

to complete this issue, `display_resistance` and `display_capacitance` need to be added as optional string properties to the zod schema in the circuit-json repo

**Comment by Anshgrover23** [comment]
@seveibar added the properties to the circuit-json https://github.com/tscircuit/circuit-json/pull/111/

**Comment by Abse2001** [comment]
@Anshgrover23 I merged your PR https://github.com/tscircuit/circuit-json/pull/111/
update the dependencies and make sure that the tests are passing then tag me for a review.

**Comment by Anshgrover23** [comment]
@Abse2001 done.

**Review by Abse2001 — APPROVED** [review]

**Review by seveibar — APPROVED** [review]
nice work

**Comment by Anshgrover23** [comment]
@seveibar thanks.

**Pull request merged**
