### PR TITLE
chore: update package to smaller bundle size

### PR DESCRIPTION
**Pull request by imrishabh18**

### CODE REVIEW

**Comment by imrishabh18** [comment]
@seveibar Damn this is nice! The `soup-util` was having unused `bun/types` package

**Comment by imrishabh18** [comment]
Looking in `circuit-json` if I can find something

**Comment by seveibar** [comment]
Very nice, still suspiciously high # of files for soup-util (i think there should only be dist/index.js) but looking good!!

**Comment by imrishabh18** [comment]
There is only one `index.js` file

Screenshot 2024-10-08 at 12 23 23 AM

**Comment by seveibar** [comment]
Why does the bundle size analysis show 31 files?

**Comment by seveibar** [comment]
Im actually not sure. Maybe not an issue

**Comment by imrishabh18** [comment]
Even I am not sure, most of the packages are just only the `index.js` in the dist folder but still the bundle analysis is showing a lot of files

Screenshot 2024-10-08 at 12 28 56 AM

**Pull request merged**
