### PR TITLE
added pcb_silkscreen_text ccw_rotation

### PR DESCRIPTION
**Pull request by Abse2001**
please approve circuit-json PR first : [circuit-json PR](https://github.com/tscircuit/circuit-json/pull/101)

### CODE REVIEW

**Comment by Abse2001** [comment]
@seve I will re-run the workflows after merging circuit-json and installing the latest version

**Review by seveibar — APPROVED** [review]
always good to have a test too!

**Comment by seve** [comment]
👋

**Comment by Abse2001** [comment]
@seve sorry wrong tag my bad lol

**Pull request closed without merging**
