### PR TITLE
updated to circuit-json and added pcb_trace_id to via

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**

### CODE REVIEW

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
make sure to get typecheck to pass

**Comment by ShiboSoftwareDev** [comment]
@seveibar what about the size check

**Comment by seveibar** [comment]
@ShiboSoftwareDev the size check doesn't work against forks right now unfortunately

**Comment by ShiboSoftwareDev** [comment]
@seveibar check the latest change, I'll just add an issue to update autorouting dataset and footprinter on this repo

**Review by seveibar — APPROVED** [review]
NICE

**Pull request merged**
