### PR TITLE
Refactor the trace so it does not get passed to the chip manufacturer part number and name

### LINKED ISSUE #307: Don't wire through manufacturer labels in schematic
This requires moving the manufacturer labels as a `schematic_text` core output, rather than inserting inside of `circuit-to-svg`

Image

/bounty $30

### PR DESCRIPTION
**Pull request by anas-sarkez**
this issue fixed with converting manufacturer labels as a `schematic_text`
/claim #307
fixed #307 
**this example before fixed the issue**

Screenshot 2024-11-17 at 9 16 07 PM

**this is after fixed** 
Screenshot 2024-11-17 at 9 48 13 PM

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
this looks great but we should update all the snapshots to see if it causes any issues

**Comment by anas-sarkez** [comment]
> this looks great but we should update all the snapshots to see if it causes any issues
All of schematic snapshots are changed _(color is black now)_
Screenshot 2024-11-17 at 10 09 03 PM

**Comment by anas-sarkez** [comment]
Screenshot 2024-11-17 at 10 14 12 PM

**Comment by seveibar** [comment]
@anas-sarkez this looks good but you need to update all the snapshots before i can approve it

**Comment by anas-sarkez** [comment]
I will generate new snapshot test for all

**Comment by anas-sarkez** [comment]
@seveibar  should I marge?

**Comment by seveibar** [comment]
@anas-sarkez no i need to review the snapshots, let me check

**Review by seveibar — APPROVED** [review]
ok this is good, but please update circuit-to-svg to stop drawing the manufacturer part numbers because the double-layer looks bad

great work!

**Comment by anas-sarkez** [comment]
> ok this is good, but please update circuit-to-svg to stop drawing the manufacturer part numbers because the double-layer looks bad
> 
> great work!

Ok

**Comment by anas-sarkez** [comment]
> ok this is good, but please update circuit-to-svg to stop drawing the manufacturer part numbers because the double-layer looks bad
> 
> great work!

https://github.com/tscircuit/circuit-to-svg/pull/133

**Pull request merged**
